package DesignSystem.System.sandbox;

/*Generated by MPS */


public class CounterTheme extends Material {
  public static CounterTheme instance = null;



  private final Integer buttonSize;

  public CounterTheme(Integer buttonSize, Material.ColorSwatch colorSwatch, Material.TextTheme textTheme, Material.Function_309sir_c0a textButtonTheme, Material.Function_309sir_d0a outlineButtonTheme) {
    super(colorSwatch, textTheme, textButtonTheme, outlineButtonTheme);
    this.buttonSize = buttonSize;
  }

  public Integer getButtonSize() {
    return buttonSize;
  }
}
