package DesignSystem.App.sandbox;

/*Generated by MPS */

import java.awt.Color;

public abstract class ColorTokens {
  public Color getRed() {
    return "0xff0000";
  }
  public abstract Color getGreen();
  public abstract Color getBlue();
}
