package DesignSystem.App.sandbox;

/*Generated by MPS */

import java.awt.Color;

public class LightColorTokens extends ColorTokens {
  public Color green() {
    return "0x00af00";
  }
  public Color blue() {
    return "0x0000af";
  }
}
