package DesignSystem.System.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class DirectReferenceDesignSystemParentConcept_SubstituteMenu extends SubstituteMenuBase {
  public DirectReferenceDesignSystemParentConcept_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for DirectReferenceDesignSystemParentConcept. Generated from implicit smart reference attribute.", new SNodePointer("r:291ddc1b-d6e7-4ca6-a0e2-a1fae46ab1b7(DesignSystem.System.structure)", "473053312768843525")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_4i3of8_a(), CONCEPTS.DirectReferenceDesignSystemParentConcept$Bq));
    result.add(new SMP_Subconcepts_4i3of8_b());
    return result;
  }

  public class SMP_ReferenceScope_4i3of8_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_4i3of8_a() {
      super(CONCEPTS.DirectReferenceDesignSystemParentConcept$Bq, LINKS.designSystemConcept$PxdX, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_4i3of8_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_4i3of8_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "DirectReferenceDesignSystemParentConcept", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.DirectReferenceDesignSystemParentConcept$Bq);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DirectReferenceDesignSystemParentConcept$Bq = MetaAdapterFactory.getConcept(0x43e160c7168c4805L, 0x904bc45c336610e7L, 0x6909f7b4b689f05L, "DesignSystem.System.structure.DirectReferenceDesignSystemParentConcept");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink designSystemConcept$PxdX = MetaAdapterFactory.getReferenceLink(0x43e160c7168c4805L, 0x904bc45c336610e7L, 0x6909f7b4b689f05L, 0x6909f7b4b689f06L, "designSystemConcept");
  }
}
