package DesignSystem.System.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class DesignSystemParentDotSyntaxFactory {
  public static class NodeFactory_473053312771238599 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      {
        final SNode original = sampleNode;
        if (SNodeOperations.isInstanceOf(original, CONCEPTS.ReferenceDesignSystemParentConcept$Zz)) {
          SLinkOperations.setTarget(newNode, LINKS.parent$OA8y, original);
        }
      }
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ReferenceDesignSystemParentConcept$Zz = MetaAdapterFactory.getConcept(0x43e160c7168c4805L, 0x904bc45c336610e7L, 0x6909f7b4b864160L, "DesignSystem.System.structure.ReferenceDesignSystemParentConcept");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink parent$OA8y = MetaAdapterFactory.getContainmentLink(0x43e160c7168c4805L, 0x904bc45c336610e7L, 0x6909f7b4b81ef0aL, 0x6909f7b4b864161L, "parent");
  }
}
