graph TD
    Designer(Designer)
    Figma((Figma))
    Entwickler(Entwickler)
    Code((Code))

    Designer -- bearbeitet --> Figma
    Designer -- gibt bescheid --> Entwickler
    Entwickler -- schaut nach --> Figma
    Entwickler -- bearbeitet --> Code