package json.model.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class JSONNumber_Constraints extends BaseConstraintsDescriptor {
  public JSONNumber_Constraints() {
    super(CONCEPTS.JSONNumber$ro);
  }

  @Override
  public SConcept getDefaultConcreteConcept() {
    return CONCEPTS.JSONInteger$cn;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept JSONNumber$ro = MetaAdapterFactory.getConcept(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, 0x515a2af4d2695d5L, "json.model.structure.JSONNumber");
    /*package*/ static final SConcept JSONInteger$cn = MetaAdapterFactory.getConcept(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, 0x515a2af4d2695cbL, "json.model.structure.JSONInteger");
  }
}
