package ARD.Player.Model.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.MapConfigBase;
import jetbrains.mps.generator.runtime.TemplateMappingConfiguration;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateReductionRule;
import jetbrains.mps.generator.runtime.TemplateRootMappingRule;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateModel;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.runtime.ReductionRuleBase;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import jetbrains.mps.generator.runtime.MapRootRuleBase;
import jetbrains.mps.generator.runtime.MetaObjectContainer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

@Generated
public class Mapping_main extends MapConfigBase implements TemplateMappingConfiguration {
  private final Collection<TemplateReductionRule> rules;
  private final Collection<TemplateRootMappingRule> rootRules;
  public Mapping_main(@NotNull TemplateModel model) {
    super(new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423831197"), "main", model, false, new MO());
    rules = TemplateUtil.<TemplateReductionRule>asCollection(new ReductionRule0(), new ReductionRule1(), new ReductionRule2(), new ReductionRule3(), new ReductionRule4(), new ReductionRule5(), new ReductionRule6());
    rootRules = TemplateUtil.<TemplateRootMappingRule>asCollection(new RootMappingRule0());
  }
  @Override
  public Collection<TemplateReductionRule> getReductionRules() {
    return rules;
  }
  @Override
  public Collection<TemplateRootMappingRule> getRootRules() {
    return rootRules;
  }
  /*package*/ final class ReductionRule0 extends ReductionRuleBase {
    public ReductionRule0() {
      super(new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423910898"), CONCEPTS.EmbeddedConfig$lz, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = environment.callSite(new Template_reduce_EmbeddedConfig(), new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423910899")).apply(context);
      return tlist1;
    }
  }
  /*package*/ final class ReductionRule1 extends ReductionRuleBase {
    public ReductionRule1() {
      super(new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423913001"), CONCEPTS.GenericConfig$74, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = environment.callSite(new Template_reduce_GenericConfig(), new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423913002")).apply(context);
      return tlist1;
    }
  }
  /*package*/ final class ReductionRule2 extends ReductionRuleBase {
    public ReductionRule2() {
      super(new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423919497"), CONCEPTS.PluginConfig$46, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = environment.callSite(new Template_reduce_PluginConfig(), new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423919498")).apply(context);
      return tlist1;
    }
  }
  /*package*/ final class ReductionRule3 extends ReductionRuleBase {
    public ReductionRule3() {
      super(new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423940376"), CONCEPTS.WebConfig$KE, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = environment.callSite(new Template_reduce_WebConfig(), new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423940377")).apply(context);
      return tlist1;
    }
  }
  /*package*/ final class ReductionRule4 extends ReductionRuleBase {
    public ReductionRule4() {
      super(new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753829705"), CONCEPTS.ImageTemplateConfig$sf, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = environment.callSite(new Template_reduce_ImageTemplateConfig(), new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753829706")).apply(context);
      return tlist1;
    }
  }
  /*package*/ final class ReductionRule5 extends ReductionRuleBase {
    public ReductionRule5() {
      super(new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753830762"), CONCEPTS.ImageTemplateNamedSizeConfig$EL, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = environment.callSite(new Template_reduce_ImageTemplateNamedSizeConfig(), new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753830763")).apply(context);
      return tlist1;
    }
  }
  /*package*/ final class ReductionRule6 extends ReductionRuleBase {
    public ReductionRule6() {
      super(new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753831180"), CONCEPTS.ImageTemplateWidthConfig$CP, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> tlist1 = environment.callSite(new Template_reduce_ImageTemplateWidthConfig(), new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753831181")).apply(context);
      return tlist1;
    }
  }
  /*package*/ final class RootMappingRule0 extends MapRootRuleBase implements TemplateRootMappingRule {
    public RootMappingRule0() {
      super(new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423957574"), CONCEPTS.PlayerConfig$YC, false, false);
    }
    @Override
    public Collection<SNode> apply(@NotNull final TemplateContext context) throws GenerationException {
      final TemplateExecutionEnvironment environment = context.getEnvironment();
      Collection<SNode> result = environment.callSite(new Template_map_PlayerConfig(), new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423957574")).apply(context);
      return result;
    }
  }

  /*package*/ static final class MO implements MetaObjectContainer {



  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept EmbeddedConfig$lz = MetaAdapterFactory.getConcept(0xc08689bf220f44e0L, 0xb1176fee592c62ccL, 0x271165bbd10cba3eL, "ARD.Player.Model.structure.EmbeddedConfig");
    /*package*/ static final SConcept GenericConfig$74 = MetaAdapterFactory.getConcept(0xc08689bf220f44e0L, 0xb1176fee592c62ccL, 0x271165bbd10cba8aL, "ARD.Player.Model.structure.GenericConfig");
    /*package*/ static final SConcept PluginConfig$46 = MetaAdapterFactory.getConcept(0xc08689bf220f44e0L, 0xb1176fee592c62ccL, 0x271165bbd10cbab4L, "ARD.Player.Model.structure.PluginConfig");
    /*package*/ static final SConcept WebConfig$KE = MetaAdapterFactory.getConcept(0xc08689bf220f44e0L, 0xb1176fee592c62ccL, 0x271165bbd10cbad1L, "ARD.Player.Model.structure.WebConfig");
    /*package*/ static final SConcept ImageTemplateConfig$sf = MetaAdapterFactory.getConcept(0xc08689bf220f44e0L, 0xb1176fee592c62ccL, 0x6909f7b4a82e594L, "ARD.Player.Model.structure.ImageTemplateConfig");
    /*package*/ static final SConcept ImageTemplateNamedSizeConfig$EL = MetaAdapterFactory.getConcept(0xc08689bf220f44e0L, 0xb1176fee592c62ccL, 0x6909f7b4a82e59dL, "ARD.Player.Model.structure.ImageTemplateNamedSizeConfig");
    /*package*/ static final SConcept ImageTemplateWidthConfig$CP = MetaAdapterFactory.getConcept(0xc08689bf220f44e0L, 0xb1176fee592c62ccL, 0x6909f7b4a82e599L, "ARD.Player.Model.structure.ImageTemplateWidthConfig");
    /*package*/ static final SConcept PlayerConfig$YC = MetaAdapterFactory.getConcept(0xc08689bf220f44e0L, 0xb1176fee592c62ccL, 0x271165bbd10cc22cL, "ARD.Player.Model.structure.PlayerConfig");
  }
}
