package ARD.Player.Model.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.generator.runtime.FragmentResult;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.Collection;
import java.util.Collections;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.runtime.ApplySink;
import jetbrains.mps.generator.runtime.MetaObjectContainer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class Template_reduce_EmbeddedConfig extends TemplateDeclarationBase {

  public Template_reduce_EmbeddedConfig() {
    super(new MO());
  }

  public SNodeReference getTemplateNode() {
    return new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423910896");
  }


  protected FragmentResult applyPart0(@NotNull final TemplateContext context) throws GenerationException {
    final TemplateExecutionEnvironment environment = context.getEnvironment();
    final SNode tnode1 = environment.createOutputNode(myConcepts[0]);
    {
      TemplateContext context1 = context.subContext();
      {
        Collection<SNode> tlist2 = Collections.emptyList();
        if (QueriesGenerated.ifMacro_Condition_1_0(new IfMacroContext(context1, ifMacroRef))) {
          final SNode tnode3 = environment.createOutputNode(myConcepts[1]);
          {
            tnode3.setProperty(myProperties[0], "baseUrl");
            TemplateContext context2 = context1.subContext();
            {
              Collection<SNode> tlist4 = null;
              final SNode copySrcInput4 = QueriesGenerated.sourceNodeQuery_1_0(new SourceSubstituteMacroNodeContext(context2, copySrcMacro));
              tlist4 = environment.copyNodes(TemplateUtil.singletonList(copySrcInput4), copySrcMacro, "tpl/r:06cdd5b9-ab92-4965-9423-c07eea1d6828/2815143099423912613", context2);
              environment.aggregate(tnode3, myAggregationLinks[0], tlist4);
            }
          }
          tlist2 = TemplateUtil.singletonList(tnode3);
        }
        environment.aggregate(tnode1, myAggregationLinks[1], tlist2);
      }
      {
        Collection<SNode> tlist5 = Collections.emptyList();
        if (QueriesGenerated.ifMacro_Condition_1_1(new IfMacroContext(context1, ifMacroRef1))) {
          final SNode tnode6 = environment.createOutputNode(myConcepts[1]);
          {
            tnode6.setProperty(myProperties[0], "allowAutoplay");
            TemplateContext context3 = context1.subContext();
            {
              Collection<SNode> tlist7 = null;
              final SNode copySrcInput7 = QueriesGenerated.sourceNodeQuery_1_1(new SourceSubstituteMacroNodeContext(context3, copySrcMacro1));
              tlist7 = environment.copyNodes(TemplateUtil.singletonList(copySrcInput7), copySrcMacro1, "tpl/r:06cdd5b9-ab92-4965-9423-c07eea1d6828/2815143099423912917", context3);
              environment.aggregate(tnode6, myAggregationLinks[0], tlist7);
            }
          }
          tlist5 = TemplateUtil.singletonList(tnode6);
        }
        environment.aggregate(tnode1, myAggregationLinks[1], tlist5);
      }
    }
    FragmentResult rv = nodeFragment(2, tnode1);
    return rv;
  }
  @Override
  public void apply(TemplateContext context, ApplySink sink) throws GenerationException {
    applyPart0(context).reportTo(sink);
  }

  /*package*/ static final class MO implements MetaObjectContainer {
    @Override
    public SConcept[] concepts() {
      SConcept[] rv = new SConcept[2];
      rv[0] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, "json.model"), 0x515a2af4d2695b7L, "JSONObject");
      rv[1] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, "json.model"), 0x515a2af4d2695f0L, "JSONObjectEntry");
      return rv;
    }

    @Override
    public SProperty[] properties() {
      SProperty[] rv = new SProperty[1];
      rv[0] = MetaAdapterFactory.getProperty(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, 0x515a2af4d2695f0L, 0x515a2af4d2695f7L, "key");
      return rv;
    }


    @Override
    public SContainmentLink[] aggregations() {
      SContainmentLink[] rv = new SContainmentLink[3];
      rv[0] = MetaAdapterFactory.getContainmentLink(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, 0x515a2af4d2695f0L, 0x515a2af4d2695fbL, "value");
      rv[1] = MetaAdapterFactory.getContainmentLink(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, 0x515a2af4d2695b7L, 0x515a2af4d2695fdL, "value");
      rv[2] = MetaAdapterFactory.getContainmentLink(0xb401a68083254110L, 0x8fd384331ff25befL, 0xfe43cb41d0L, 0xfe43de823bL, "contentNode");
      return rv;
    }
  }
  private static final SNodePointer copySrcMacro = new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423912617");
  private static final SNodePointer ifMacroRef = new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753549653");
  private static final SNodePointer copySrcMacro1 = new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "2815143099423912921");
  private static final SNodePointer ifMacroRef1 = new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753558276");
}
