package ARD.Player.Model.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.generator.runtime.FragmentResult;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.Collection;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.generator.runtime.ApplySink;
import jetbrains.mps.generator.runtime.MetaObjectContainer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class Template_reduce_ImageTemplateConfig extends TemplateDeclarationBase {

  public Template_reduce_ImageTemplateConfig() {
    super(new MO());
  }

  public SNodeReference getTemplateNode() {
    return new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753829703");
  }


  protected FragmentResult applyPart0(@NotNull final TemplateContext context) throws GenerationException {
    final TemplateExecutionEnvironment environment = context.getEnvironment();
    final SNode tnode1 = environment.createOutputNode(myConcepts[0]);
    {
      TemplateContext context1 = context.subContext();
      {
        final SNode tnode2 = environment.createOutputNode(myConcepts[1]);
        {
          tnode2.setProperty(myProperties[0], "width");
          TemplateContext context2 = context1.subContext();
          {
            Collection<SNode> tlist3 = null;
            final SNode copySrcInput3 = QueriesGenerated.sourceNodeQuery_6_0(new SourceSubstituteMacroNodeContext(context2, copySrcMacro));
            tlist3 = environment.copyNodes(TemplateUtil.singletonList(copySrcInput3), copySrcMacro, "tpl/r:06cdd5b9-ab92-4965-9423-c07eea1d6828/473053312753829733", context2);
            environment.aggregate(tnode2, myAggregationLinks[0], tlist3);
          }
        }
        environment.aggregate(tnode1, myAggregationLinks[1], tnode2);
      }
      {
        final SNode tnode4 = environment.createOutputNode(myConcepts[1]);
        {
          tnode4.setProperty(myProperties[0], "size");
          TemplateContext context3 = context1.subContext();
          {
            final SNode tnode5 = environment.createOutputNode(myConcepts[2]);
            {
              TemplateContext context4 = context3.subContext();
              {
                Collection<SNode> tlist6 = null;
                final Iterable<SNode> copyListInput6 = QueriesGenerated.sourceNodesQuery_6_0(new SourceSubstituteMacroNodesContext(context4, copySrcListMacro));
                tlist6 = environment.copyNodes(copyListInput6, copySrcListMacro, "tpl/r:06cdd5b9-ab92-4965-9423-c07eea1d6828/473053312753830039", context4);
                environment.aggregate(tnode5, myAggregationLinks[2], tlist6);
              }
            }
            environment.aggregate(tnode4, myAggregationLinks[0], tnode5);
          }
        }
        environment.aggregate(tnode1, myAggregationLinks[1], tnode4);
      }
    }
    FragmentResult rv = nodeFragment(3, tnode1);
    return rv;
  }
  @Override
  public void apply(TemplateContext context, ApplySink sink) throws GenerationException {
    applyPart0(context).reportTo(sink);
  }

  /*package*/ static final class MO implements MetaObjectContainer {
    @Override
    public SConcept[] concepts() {
      SConcept[] rv = new SConcept[3];
      rv[0] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, "json.model"), 0x515a2af4d2695b7L, "JSONObject");
      rv[1] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, "json.model"), 0x515a2af4d2695f0L, "JSONObjectEntry");
      rv[2] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, "json.model"), 0x515a2af4d2695bcL, "JSONArray");
      return rv;
    }

    @Override
    public SProperty[] properties() {
      SProperty[] rv = new SProperty[1];
      rv[0] = MetaAdapterFactory.getProperty(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, 0x515a2af4d2695f0L, 0x515a2af4d2695f7L, "key");
      return rv;
    }


    @Override
    public SContainmentLink[] aggregations() {
      SContainmentLink[] rv = new SContainmentLink[4];
      rv[0] = MetaAdapterFactory.getContainmentLink(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, 0x515a2af4d2695f0L, 0x515a2af4d2695fbL, "value");
      rv[1] = MetaAdapterFactory.getContainmentLink(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, 0x515a2af4d2695b7L, 0x515a2af4d2695fdL, "value");
      rv[2] = MetaAdapterFactory.getContainmentLink(0xbbf76c73c6c840c0L, 0xab7b9998034e6ff8L, 0x515a2af4d2695bcL, 0x515a2af4d2695e3L, "value");
      rv[3] = MetaAdapterFactory.getContainmentLink(0xb401a68083254110L, 0x8fd384331ff25befL, 0xfe43cb41d0L, 0xfe43de823bL, "contentNode");
      return rv;
    }
  }
  private static final SNodePointer copySrcMacro = new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753829737");
  private static final SNodePointer copySrcListMacro = new SNodePointer("r:06cdd5b9-ab92-4965-9423-c07eea1d6828(ARD.Player.Model.generator.templates@generator)", "473053312753830042");
}
