package json.file.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import json.file.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.JSONFile:
        return new JSONFile_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.JSONFile$sn)) {
        String fname = getFileName_JSONFile(root);
        String ext = getFileExtension_JSONFile(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), getPath_JSONFile(root), root);
        continue;
      }
    }
  }
  private static String getFileName_JSONFile(SNode node) {
    return SPropertyOperations.getString(node, PROPS.name$MnvL);
  }
  private static String getFileExtension_JSONFile(SNode node) {
    return "g.json";
  }
  private static String getPath_JSONFile(SNode node) {
    return SPropertyOperations.getString(node, PROPS.path$BDTH);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept JSONFile$sn = MetaAdapterFactory.getConcept(0x22472c372c634f45L, 0xa6417ea7483e57ebL, 0x271165bbd10c3884L, "json.file.structure.JSONFile");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty path$BDTH = MetaAdapterFactory.getProperty(0x22472c372c634f45L, 0xa6417ea7483e57ebL, 0x271165bbd10c3884L, 0x515a2af4d35905dL, "path");
  }
}
