package DesignSystem.App.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AbstractDesignSystemPrimitiveTokenConcept = 0;
  public static final int AbstractDesignSystemPrimitiveTokensConcept = 1;
  public static final int AbstractDesignSystemPrimitiveTokensConceptReference = 2;
  public static final int DesignSystemAppConcept = 3;
  public static final int DesignSystemAppFileConcept = 4;
  public static final int DesignSystemExpressionConcept = 5;
  public static final int DesignSystemPrimitiveTokenConcept = 6;
  public static final int DesignSystemPrimitiveTokensConcept = 7;
  public static final int DesignSystemPrimitiveTokensFileConcept = 8;
  public static final int DesignSystemPrimitiveTokensSetConcept = 9;
  public static final int DesignSystemPrimitiveTokensSetFileConcept = 10;
  public static final int IValueExpresssionConstraints = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9b844d5fd3bc48e3L, 0x8d2ed303cf551efeL);
    builder.put(0x6909f7b4c087386L, AbstractDesignSystemPrimitiveTokenConcept);
    builder.put(0x6909f7b4c064ef7L, AbstractDesignSystemPrimitiveTokensConcept);
    builder.put(0x6909f7b4c0af97bL, AbstractDesignSystemPrimitiveTokensConceptReference);
    builder.put(0x6909f7b4b5e14e4L, DesignSystemAppConcept);
    builder.put(0x6909f7b4c064effL, DesignSystemAppFileConcept);
    builder.put(0x6909f7b4c2d8f03L, DesignSystemExpressionConcept);
    builder.put(0x6909f7b4c0adb91L, DesignSystemPrimitiveTokenConcept);
    builder.put(0x6909f7b4b5e14ecL, DesignSystemPrimitiveTokensConcept);
    builder.put(0x6909f7b4c0627b3L, DesignSystemPrimitiveTokensFileConcept);
    builder.put(0x6909f7b4c0665eeL, DesignSystemPrimitiveTokensSetConcept);
    builder.put(0x6909f7b4c0665efL, DesignSystemPrimitiveTokensSetFileConcept);
    builder.put(0x6909f7b4c2bf718L, IValueExpresssionConstraints);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
