package DesignSystem.System.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ColorConcept = 0;
  public static final int DesignSystemConcept = 1;
  public static final int DesignSystemPropertiesListConcept = 2;
  public static final int DesignSystemPropertyConcept = 3;
  public static final int DesignSystemPropertyParameterConcept = 4;
  public static final int DesignSystemPropertyParametersListConcept = 5;
  public static final int DesignSystemSubsystemListConcept = 6;
  public static final int IDesignSystemPropertyType = 7;
  public static final int IDesignSystemValueType = 8;
  public static final int List = 9;
  public static final int Type = 10;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x43e160c7168c4805L, 0x904bc45c336610e7L);
    builder.put(0x6909f7b4b5e1510L, ColorConcept);
    builder.put(0x6909f7b4b5e14e7L, DesignSystemConcept);
    builder.put(0x6909f7b4b5e14f2L, DesignSystemPropertiesListConcept);
    builder.put(0x6909f7b4b5e1504L, DesignSystemPropertyConcept);
    builder.put(0x6909f7b4b5e1538L, DesignSystemPropertyParameterConcept);
    builder.put(0x6909f7b4b5e152aL, DesignSystemPropertyParametersListConcept);
    builder.put(0x6909f7b4b5e14f1L, DesignSystemSubsystemListConcept);
    builder.put(0x6909f7b4b5e1509L, IDesignSystemPropertyType);
    builder.put(0x6909f7b4b5e152eL, IDesignSystemValueType);
    builder.put(0x6909f7b4b5e1531L, List);
    builder.put(0x6909f7b4b5e2e2dL, Type);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
