package DesignSystem.App.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class DesignSystemExpressionConcept_Constraints extends BaseConstraintsDescriptor {
  public DesignSystemExpressionConcept_Constraints() {
    super(CONCEPTS.DesignSystemExpressionConcept$eM);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DesignSystemExpressionConcept$eM = MetaAdapterFactory.getConcept(0x9b844d5fd3bc48e3L, 0x8d2ed303cf551efeL, 0x6909f7b4c2d8f03L, "DesignSystem.App.structure.DesignSystemExpressionConcept");
  }
}
